CREATE EXTENSION IF NOT EXISTS Postgis;

DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Position CASCADE;
DROP TABLE IF EXISTS MeetRequest CASCADE;

DROP TYPE IF EXISTS REQUEST_STATUS;
DROP TYPE IF EXISTS SEX;

CREATE TYPE SEX AS ENUM ('M', 'F', '');
CREATE TYPE REQUEST_STATUS AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED', 'INTERRUPTED');

CREATE TABLE Users (
  id       SERIAL PRIMARY KEY,
  login    VARCHAR(50) UNIQUE ,
  password BYTEA,
  sex      SEX NOT NULL DEFAULT '',
  age      INT,
  about    VARCHAR(1000)
);

CREATE TABLE Position (
  id     SERIAL PRIMARY KEY,
  userId INTEGER REFERENCES Users (id),
  point  GEOMETRY,
  time   TIMESTAMP DEFAULT now()
);

CREATE TABLE MeetRequest (
  id SERIAL PRIMARY KEY,
  time TIMESTAMP DEFAULT now(),
  requesterId INT REFERENCES Users(id),
  requestedId INT REFERENCES Users(id),
  status REQUEST_STATUS DEFAULT 'PENDING'
);
