CREATE EXTENSION IF NOT EXISTS Postgis;

DROP TABLE IF EXISTS Users CASCADE;

DROP TYPE IF EXISTS SEX;

CREATE TYPE SEX AS ENUM ('M', 'F', '');

CREATE TABLE Users (
  id       SERIAL PRIMARY KEY,
  login    VARCHAR(50) UNIQUE ,
  password BYTEA,
  sex      SEX NOT NULL DEFAULT '',
  age      INT,
  about    VARCHAR(1000)
);
