swagger: '2.0'

# This is your document metadata
info:
  version: "0.1.0"
  title: API сервера знакомств

# Describe your paths here
paths:
  /api/v1/auth/register:
    post:
      summary:
        Регистрация пользователя
      parameters:
        - name: user
          in: body
          description: Информация о пользователе
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description:
            пользователь успешно зарегистрирован.
          schema:
            type: object
            description: ответ с токеном авторизации
            example:
              {
                data: token_of_the_user
              }
        400:
          description:
            ошибка в запросе
          schema:
            type: object
            description: ответ с ошибкой
            example:
              {
                err_msg: плохой запрос
              }
        409:
          description:
            пользователь уже присутствует в базе данных
          schema:
            type: object
            description: ответ с ошибкой
            example:
              {
                err_msg: конфликт
              }
        500:
          description:
            ошибка на сервере
          schema:
            type: object
            description: ответ с ошибкой
            example:
              {
                err_msg: сервер упал
              }

  /api/v1/auth/login:
    post:
      summary:
        Логин пользователя
      parameters:
        - name: login
          in: body
          description: Информация о пользователе
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description:
            пользователь успешно зарегистрирован.
          schema:
            type: object
            description: ответ с токеном авторизации
            example:
              {
                data: token_of_the_user
              }
        400:
          description:
            ошибка в запросе
          schema:
            type: object
            description: ответ с ошибкой
            example:
              {
                err_msg: плохой запрос
              }
        404:
          description:
            пользователь не найден в базе
          schema:
            type: object
            description: ответ с ошибкой
            example:
              {
                err_msg: пользователь не найден
              }
        500:
          description:
            ошибка на сервере
          schema:
            type: object
            description: ответ с ошибкой
            example:
              {
                err_msg: сервер упал
              }

  /api/v1/user/self:
      get:
        summary:
          Получить информацию о самом себе
        parameters:
          - name: Authorization
            in: header
            description: авторизационный токен
            required: true
            type: string
        responses:
          200:
            description:
              данные успешно получены
            schema:
              type: object
              description: информация о себе
              example:
                {
                  "data": $ref: '#/definitions/User'
                }
          400:
            description:
              проблема с авторизационным токеном
            schema:
              type: object
              description: ответ с ошибкой
              example:
                {
                  err_msg: плохой запрос
                }
          500:
            description:
              ошибка на сервере
            schema:
              type: object
              description: ответ с ошибкой
              example:
                {
                  err_msg: сервер упал
                }

definitions:
  User:
    type: object
    properties:
      login:
        type: string
        description: Логин пользователя
        example: Petya
      password:
        type: string
        description: Пароль пользователя
        example: some78pass
      age:
        type: integer
        description: Возраст пользователя
        example: 15
      sex:
        type: string
        description: Пол пользователя (M или F)
        example: M
      about:
        type: string
        description: Все, что пользователь хочет сообщить о себе
        example: Мне нечего сказать о себе
    required:
    - login
    - password
